[package]
name = "listener"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.10.29"
solana-program = "1.10.29"
solana-sdk = "1.10.29"
solana-transaction-status = "1.10.29"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
